### ISSUE TITLE
"Required packages" can (wrongly) suggest that user needs to handle them

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Cog-Browser#10]
This might a problem that's not worth pursuing, but since I've seen a person ask how to install the required packages listed in Index, I wanted to at least bring it up to the table so that it's there for reference even if it's not pursued.

**Comment by Eslyium** [comment]
Jack --

Are you saying we should just remove the required packages part?
Whats your opinion on it?

**Comment by Jackenmen** [comment]
I would say that yes, we should just hide the required packages (imo except bot version requirements, it is handled by Downloader too but I would hope that all it can really do is let user know they should update their bot). I guess we could maybe make it collapsible (collapsed by default) if some people think this serves useful information, but personally I don't really think it's necessary.

Might also want to get other's opinion here too.

**Comment by Drapersniper** [comment]
I would suggest renaming, rather than remove. Like cog 3rd party libs or something of that sort

**Comment by Jackenmen** [comment]
Yeah, I agree that the rename will probably be enough to help us avoid misleading the user.
I think in addition to that, we should make it show collapsed by default (if possible with not much effort) to help reduce this issue even more.

Few names that have been suggested (there wasn't much feedback though, so we might need to try asking again):
- This cog is using libraries:
- Libraries used by this cog:
- This cog is using libraries listed below
- External libraries used:
- ???

**Comment by Eslyium** [comment]
Will take a look at getting this done before end of week.

**Comment by Eslyium** [comment]
Renamed Required packages -> Bot Version And Packages Used
(Hard to word this but if have other suggestions let me know)
