### ISSUE TITLE
Clicking 'Next' From Start Page Is Bugged

### ISSUE THREAD

**Issue by Menteroth** [Cog-Creators/Cog-Browser#15]
So if I search for a cog and go back to start page and go down to the bottom of the page, with an empty search field, to click next I am moved to an empty page and also what I last searched for instead of having page 2 of 17 listed.
![image](https://user-images.githubusercontent.com/24851042/99039110-08009280-2587-11eb-80a2-5075107491b1.png)

I tried this with a new profile in Chrome and it worked to click next the first time but after searching for a cog and going back to start page and clicking next from there same thing happens.

Google Chrome
Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by Jackenmen** [comment]
I actually had that happen to me before. It appears that there's some caching issue which makes an old search term get used when you're browsing whole cog list without search term.

**Comment by Eslyium** [comment]
Done.
